[package]
name = "fairy-spider"
version = "0.1.0"
edition = "2021"
authors = ["Gabriel Conrado <gabaconrado@gmail.com>"]
description = "Minimal OS based on the 'Writing an OS in Rust' series"
readme = "README.md"
repository = "https://github.com/gabaconrado/fairy-spider"
license = "MIT"
keywords = ["os", "study"]
categories = ["os", "no-std"]

[dependencies]
bootloader = "0.9"

[lints]
clippy.as_conversions = "deny"
clippy.expect_used = "deny"
clippy.indexing_slicing = "deny"
clippy.let_underscore_future = "deny"
clippy.panic = "deny"
clippy.mod_module_files = "deny"
clippy.todo = "deny"
clippy.unimplemented = "deny"
clippy.unreachable = "deny"
clippy.unwrap_used = "deny"
rust.missing_debug_implementations = "deny"
rust.missing_docs = "deny"
rust.trivial_casts = "deny"
rust.trivial_numeric_casts = "deny"
rust.unused_extern_crates = "deny"
rust.unused_import_braces = "deny"
rust.unused_qualifications = "deny"
rust.unused_results = "deny"
rust.warnings = "deny"
